language: cpp
dist: xenial
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - sourceline: deb https://apt.kitware.com/ubuntu/ xenial main
        key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    packages: [cmake, ninja-build]
  homebrew:
    update: true
    packages: [cmake, ninja]
script:
  # Work around Travis's broken CMake configuration.
  - export PATH=$(echo $PATH | sed -e 's|:[^:]*cmake[^:]*:|:|g')
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -S . -B build
  - cmake --build ./build
  - cd ./build && ctest --output-on-failure
